[project]
name = "sudoku"
version = "0.1.0"
description = "An online multiplayer sudoku app."
dependencies = [
  "flask",
  "gunicorn",
  "requests",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"