DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  board_id INTEGER
);

CREATE TABLE boards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  board TEXT NOT NULL
);
